kind: pipeline
name: production
type: docker

when:
  event: [ push ]
  branch: [ main ]

steps:
  - name: build
    image: rust
    commands:
      - cargo build --verbose
  - name: test
    image: rust
    commands:
      - cargo test --verbose
